export const reportItemsArray = [
  {
    title: "24/7 customer support",
    description: "Success in each case",
  },
  {
    title: "10+ years experience",
    description: "In the Travel Industry",
  },
  {
    title: "unpublished inventory",
    description: "From all over the world",
  },
  {
    title: "best rates and experience",
    description: "At your service",
  },
];

export const forePhoneNumbers = [
  "93",
  "355",
  "213",
  "684",
  "376",
  "244",
  "264",
  "672",
  "268",
  "54",
  "374",
  "297",
  "61",
  "43",
  "994",
  "242",
  "973",
  "880",
  "246",
  "375",
  "32",
  "501",
  "229",
  "441",
  "975",
  "591",
  "387",
  "267",
  "55",
  "673",
  "359",
  "226",
  "257",
  "855",
  "237",
  "1",
  "238",
  "345",
  "236",
  "235",
  "56",
  "86",
  "53",
  "61",
  "57",
  "269",
  "243",
  "242",
  "682",
  "506",
  "225",
  "385",
  "53",
  "357",
  "420",
  "45",
  "253",
  "767",
  "809",
  "670",
  "593",
  "20",
  "503",
  "240",
  "291",
  "372",
  "251",
  "500",
  "298",
  "679",
  "358",
  "33",
  "594",
  "689",
  "241",
  "220",
  "995",
  "49",
  "233",
  "350",
  "30",
  "299",
  "473",
  "590",
  "671",
  "502",
  "224",
  "245",
  "592",
  "509",
  "504",
  "852",
  "36",
  "354",
  "91",
  "62",
  "98",
  "964",
  "353",
  "972",
  "39",
  "876",
  "81",
  "962",
  "7",
  "254",
  "686",
  "850",
  "82",
  "965",
  "996",
  "856",
  "371",
  "961",
  "266",
  "231",
  "218",
  "423",
  "370",
  "352",
  "853",
  "389",
  "261",
  "265",
  "60",
  "960",
  "223",
  "356",
  "692",
  "596",
  "222",
  "230",
  "269",
  "52",
  "691",
  "373",
  "377",
  "976",
  "664",
  "212",
  "258",
  "95",
  "264",
  "674",
  "977",
  "31",
  "599",
  "687",
  "64",
  "505",
  "227",
  "234",
  "683",
  "672",
  "670",
  "47",
  "968",
  "92",
  "680",
  "970",
  "507",
  "675",
  "595",
  "51",
  "63",
  "48",
  "351",
  "787",
  "974",
  "262",
  "40",
  "7",
  "250",
  "290",
  "869",
  "758",
  "508",
  "784",
  "685",
  "378",
  "239",
  "966",
  "221",
  "248",
  "232",
  "65",
  "421",
  "386",
  "677",
  "252",
  "27",
  "34",
  "94",
  "249",
  "597",
  "268",
  "46",
  "41",
  "963",
  "886",
  "992",
  "255",
  "66",
  "690",
  "676",
  "868",
  "216",
  "90",
  "993",
  "649",
  "688",
  "256",
  "380",
  "971",
  "44",
  "1",
  "598",
  "998",
  "678",
  "418",
  "58",
  "84",
  "284",
  "340",
  "681",
  "967",
  "260",
  "263",
];

export const DetailCardsData = [
  {
    imgURL: "/assets/img/main/dubai.png",
    city: "Dubai",
    price: "$2,499",
    from: "UNITED ARAB EMIRATES",
  },
  {
    imgURL: "/assets/img/main/sydney.png",
    city: "Sydney",
    price: "$2,997",
    from: "AUSTRALIA",
  },
  {
    imgURL: "/assets/img/main/tokyo.png",
    city: "Tokyo",
    price: "$2,479",
    from: "JAPAN",
  },
  {
    imgURL: "/assets/img/main/london.png",
    city: "London",
    price: "$2,322",
    from: "ENGLAND",
  },
  {
    imgURL: "/assets/img/main/casablanca.png",
    city: "Casablanca",
    price: "$2,545",
    from: "MOROCCO",
  },
  {
    imgURL: "/assets/img/main/barcelona.png",
    city: "Barcelona",
    price: "$2,244",
    from: "SPAIN",
  },
  {
    imgURL: "/assets/img/main/rome.png",
    city: "Rome",
    price: "$2,178",
    from: "ITALY",
  },
];

export const QuickLandingData = {
  france: {
    title: "air france",
    summary: `<b>Air France</b>, stylized as AIRFRANCE, is the flag carrier of France headquartered in Tremblay-en-France. It is a subsidiary of the Air France–KLM Group. It is a founding member
    of the SkyTeam global airline alliance and has a network that spans five continents. Its cabins are a popular redemption for members of partner programs like Delta SkyMiles.`,
    first: {
      content: [
        `The new first-class product is currently in the design phase and this confirms the carrier’s commitment to maintaining first class.`,
        `As it’s described, this will be “the longest cabin” on the market, and there will be a seat, a sofa, and a full flatbed.`,
        `<b>Air France</b> first class is currently available on select Boeing 777-300ERs. The current first class product, which was introduced back in 2014, features curtains that offer full privacy.`,
        `It’s a phenomenal cabin, and personally I rank <b>Air France</b> as having the second best first class experience in the air, and the best first class experience on the ground.`,
        `<b>La Première - Intercontinental flights:</b>`,
      ],
      list: [
        `A customized service`,
        `Simplified boarding`,
        `A full team at your service`,
        `Delectable cuisine`,
        `A space devoted to your well-being`,
        `Service on board`,
        `Your own personalized living space`,
        `Great entertainment, at your fingertips`,
        `Your seat, your bed`,
      ],
    },
    business: {
      content: [
        `The French carrier is currently updating its business class cabins to feature a 1-2-1 layout.`,
        `The newest designs for the Boeing 777-300ER include more modern finishes and a sliding door on each seat to add privacy. There are still a few Boeing 777/777-300 planes that have a 2-3-2 layout with middle seats in business class, so you’ll want to avoid these.`,
        `No matter which plane you fly, the typically French experience of fine dining and fashionable presentation remain highlights of flying <b>Air France</b> business class. And you can experience it by paying in cash or redeeming miles.`,
        `<b>Air France</b> likes to highlight its “Frenchness:” fine dining with chef partnerships, Champagne, tasty French cheeses and amenity kits packed with Clarins products.`,
        `On top of the French-inspired touches, <br />
         <b>Air France</b> offers many of the perks you might expect from business class.`,
        `<b>Here are some of the highlights:</b>`,
      ],
      list: [
        `Extra Bag Allowance`,
        `Priority Boarding`,
        `Flatbed Seats`,
        `Fine Dining`,
        `Business Class Lounge access`,
      ],
    },
    economy: {
      content: [
        `Premium Economy is sold on every <b>Air France</b> flight that is operated by wide-body aircraft, including the Boeing 777, Boeing 787, Airbus A330, and Airbus A350.`,
        `Premium economy products among carriers can range from being more like the economy class to being much closer to business class. The <b>Air France</b> Premium Economy products is closer to economy class than it is to business—competitors on the same routes offer more spacious seating and more upgraded meals.`,
        `<b>Air France</b> is one of the few carriers advertises the ability to purchase lounge access (subject to availability) for Premium Economy passengers. Premium Economy passengers also enjoy Sky Priority services like expedited check-in, boarding, and baggage delivery.`,
      ],
    },
  },
  british: {
    title: "british airways",
    summary: `<b>British Airways</b>is the flag carrier airline of the United Kingdom. It is headquartered in London, England, near its main hub at Heathrow Airport. It operates one of the largest and the most modern fleets of any airline in the world. It is also the second largest UK based carrier, based on fleet size and passengers carried, behind easyJet.`,
    first: {
      content: [
        `<b>British Airways</b> First Class is the most luxurious way to experience flight. From your own stylish suite, to exclusive access to lounges, fast-track security, and excellent service, it’s the finest way to travel.`,
        `Cross the world’s skies comfortably, calm, and entertained in your own spacious suite. It’s where British heritage meets contemporary design; letting you work in peace, watch a film, or stretch out and fall asleep.`,
      ],
      list: [
        `Fine dining and delicious treats`,
        `A specially designed cabin on 787-9 Dreamliner aircraft`,
        `Free Wi-Fi now available`,
        `Space to prepare and relax`,
        `The Concorde Room – the most luxurious lounge`,
        `The First Wing – express boarding`,
        `Doorstep baggage pick-up & check-in`,
        `Your seat, your bed`,
      ],
    },
    business: {
      content: [
        `<b>British Airways</b> has several classes of travel designed for the comfort of business travelers.`,
        `Travel within countries like the USA or short flights inside Europe, are generally not as luxurious as long-haul international flights.`,
        `On international flights, however, the new club suites in the brand new business class Airbus A350 -1000 might just set a new industry standard.`,
        `<b>British Airways Club World Suites:</b>`,
      ],
      list: [
        `Lie-flat seat position`,
        `Dedicated business class cabin`,
        `40% more personal storage space`,
        `A vanity area with a mirror`,
        `Wi-Fi and PC/USB power`,
        `High-definition 18.5in screen with entertainment options`,
        `Luxury bedding`,
        `Dedicated support team for all your travel needs`,
        `Restore & Relax Spa collections amenity kit`,
        `Gourmet menu options`,
      ],
    },
    economy: {
      content: [
        `Enjoy an enhanced in-flight experience with World Traveller Plus.`,
        `Flying World Traveller Plus is an exciting upgrade.`,
        `With fewer rows, the cabin is quieter, more spacious, and more exclusive.`,
      ],
      list: [
        "Wider seats and more legroom",
        "A separate, smaller cabin with attentive service",
        "Two delicious meals, complimentary bar service including signature cocktails (or mocktail)",
        "A personal entertainment system with noise-cancelling headphones",
        "Stylish amenity kit made from recycled material",
        "More free baggage allowance",
        "Priority boarding",
      ],
    },
  },
  lufthansa: {
    title: "Lufthansa",
    // summary: `<b>British Airways</b>is the flag carrier airline of the United Kingdom. It is headquartered in London, England, near its main hub at Heathrow Airport. It operates one of the largest and the most modern fleets of any airline in the world. It is also the second largest UK based carrier, based on fleet size and passengers carried, behind easyJet.`,
    first: {
      content: [
        `In <b>Lufthansa</b>’s First Class cabin, you’ll get your own suite with a considerable degree of privacy, a 17” in-flight entertainment monitor, a dazzling selection of expensive wines and spirits, a consistently excellent onboard gastronomic experience including caviar, and one of the most comfortable beds in the sky.`,
        `In addition, if you are departing or connecting in Frankfurt Airport, you have the opportunity to make use of the standalone <b>Lufthansa First Class Terminal</b>, where you can enjoy a relaxing bath with champagne on ice, a restaurant-quality dine-on-demand menu, and a well-stocked bar.`,
        `Furthermore, you’ll be personally driven to your departing flight in either a Porsche or a Mercedes-Benz, casting aside the usual grievances associated with air travel.`,
      ],
      list: [
        `Valet parking service`,
        `Personal assistant`,
        `First Class Terminal`,
        `First Class Lounges`,
        `Limousine service`,
        `Comfort on board`,
        `Culinary delights & fine wines`,
        `Entertainment world`,
      ],
    },
    business: {
      content: [
        `<b>Lufthansa</b> offers a business class product on most flights. As with many European carriers, the differences between intra-Europe Business and long haul Business are substantial – this review primarily addresses the intercontinental long haul business class experience.`,
        `It’s notable that <b>Lufthansa</b> announced upgrades to the business class seating product several years ago, but the pandemic and production delays for some of the newer aircraft planned to join the fleet mean that the existing business class product will be the standard for a few more years to come.`,
        `Passengers who prefer an open plan business class cabin instead of one with highly engineered seats with lots of plastic dividers will appreciate Lufthansa’s spacious, cushy seating.`,
      ],
      list: [
        `More baggage`,
        `More personal space`,
        `Finest dining pleasure`,
        `On-board entertainment`,
        `Relax before your departure`,
        `Lufthansa Business Lounges`,
        `Priority check-in and deplane`,
      ],
    },
    economy: {
      content: [
        `More space, more free baggage, more service – long-haul flights in Premium Economy Class offer plenty of comforts.`,
        `Consequently, you’ll enjoy a relaxed flight to your destination and will be able to head off for some sightseeing or start your meeting as soon as you arrive.`,
      ],
      list: [
        "Up to 50% more personal space",
        "Two items of free baggage",
        "Welcome drink",
        "Practical travel kit",
        "Entertainment",
      ],
    },
  },
};
